// Generated by gencpp from file dino_msg_srv/dino_msg_srvResponse.msg
// DO NOT EDIT!


#ifndef DINO_MSG_SRV_MESSAGE_DINO_MSG_SRVRESPONSE_H
#define DINO_MSG_SRV_MESSAGE_DINO_MSG_SRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dino_msg_srv
{
template <class ContainerAllocator>
struct dino_msg_srvResponse_
{
  typedef dino_msg_srvResponse_<ContainerAllocator> Type;

  dino_msg_srvResponse_()
    : dino_word()  {
    }
  dino_msg_srvResponse_(const ContainerAllocator& _alloc)
    : dino_word(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _dino_word_type;
  _dino_word_type dino_word;





  typedef boost::shared_ptr< ::dino_msg_srv::dino_msg_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dino_msg_srv::dino_msg_srvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct dino_msg_srvResponse_

typedef ::dino_msg_srv::dino_msg_srvResponse_<std::allocator<void> > dino_msg_srvResponse;

typedef boost::shared_ptr< ::dino_msg_srv::dino_msg_srvResponse > dino_msg_srvResponsePtr;
typedef boost::shared_ptr< ::dino_msg_srv::dino_msg_srvResponse const> dino_msg_srvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dino_msg_srv::dino_msg_srvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dino_msg_srv::dino_msg_srvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dino_msg_srv::dino_msg_srvResponse_<ContainerAllocator1> & lhs, const ::dino_msg_srv::dino_msg_srvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.dino_word == rhs.dino_word;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dino_msg_srv::dino_msg_srvResponse_<ContainerAllocator1> & lhs, const ::dino_msg_srv::dino_msg_srvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dino_msg_srv

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::dino_msg_srv::dino_msg_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dino_msg_srv::dino_msg_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dino_msg_srv::dino_msg_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dino_msg_srv::dino_msg_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dino_msg_srv::dino_msg_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dino_msg_srv::dino_msg_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dino_msg_srv::dino_msg_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b2ef4dcf1dfece241723e967ad64a498";
  }

  static const char* value(const ::dino_msg_srv::dino_msg_srvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb2ef4dcf1dfece24ULL;
  static const uint64_t static_value2 = 0x1723e967ad64a498ULL;
};

template<class ContainerAllocator>
struct DataType< ::dino_msg_srv::dino_msg_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dino_msg_srv/dino_msg_srvResponse";
  }

  static const char* value(const ::dino_msg_srv::dino_msg_srvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dino_msg_srv::dino_msg_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string dino_word\n"
"\n"
;
  }

  static const char* value(const ::dino_msg_srv::dino_msg_srvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dino_msg_srv::dino_msg_srvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dino_word);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct dino_msg_srvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dino_msg_srv::dino_msg_srvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dino_msg_srv::dino_msg_srvResponse_<ContainerAllocator>& v)
  {
    s << indent << "dino_word: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.dino_word);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DINO_MSG_SRV_MESSAGE_DINO_MSG_SRVRESPONSE_H
