// Generated by gencpp from file dino_msg_srv/dino_msg_srv.msg
// DO NOT EDIT!


#ifndef DINO_MSG_SRV_MESSAGE_DINO_MSG_SRV_H
#define DINO_MSG_SRV_MESSAGE_DINO_MSG_SRV_H

#include <ros/service_traits.h>


#include <dino_msg_srv/dino_msg_srvRequest.h>
#include <dino_msg_srv/dino_msg_srvResponse.h>


namespace dino_msg_srv
{

struct dino_msg_srv
{

typedef dino_msg_srvRequest Request;
typedef dino_msg_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct dino_msg_srv
} // namespace dino_msg_srv


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dino_msg_srv::dino_msg_srv > {
  static const char* value()
  {
    return "042dd73801cef57cf615837b3b757460";
  }

  static const char* value(const ::dino_msg_srv::dino_msg_srv&) { return value(); }
};

template<>
struct DataType< ::dino_msg_srv::dino_msg_srv > {
  static const char* value()
  {
    return "dino_msg_srv/dino_msg_srv";
  }

  static const char* value(const ::dino_msg_srv::dino_msg_srv&) { return value(); }
};


// service_traits::MD5Sum< ::dino_msg_srv::dino_msg_srvRequest> should match
// service_traits::MD5Sum< ::dino_msg_srv::dino_msg_srv >
template<>
struct MD5Sum< ::dino_msg_srv::dino_msg_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dino_msg_srv::dino_msg_srv >::value();
  }
  static const char* value(const ::dino_msg_srv::dino_msg_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dino_msg_srv::dino_msg_srvRequest> should match
// service_traits::DataType< ::dino_msg_srv::dino_msg_srv >
template<>
struct DataType< ::dino_msg_srv::dino_msg_srvRequest>
{
  static const char* value()
  {
    return DataType< ::dino_msg_srv::dino_msg_srv >::value();
  }
  static const char* value(const ::dino_msg_srv::dino_msg_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dino_msg_srv::dino_msg_srvResponse> should match
// service_traits::MD5Sum< ::dino_msg_srv::dino_msg_srv >
template<>
struct MD5Sum< ::dino_msg_srv::dino_msg_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dino_msg_srv::dino_msg_srv >::value();
  }
  static const char* value(const ::dino_msg_srv::dino_msg_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dino_msg_srv::dino_msg_srvResponse> should match
// service_traits::DataType< ::dino_msg_srv::dino_msg_srv >
template<>
struct DataType< ::dino_msg_srv::dino_msg_srvResponse>
{
  static const char* value()
  {
    return DataType< ::dino_msg_srv::dino_msg_srv >::value();
  }
  static const char* value(const ::dino_msg_srv::dino_msg_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DINO_MSG_SRV_MESSAGE_DINO_MSG_SRV_H
